language: r
cache: packages
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
  - secure: LmlTZkn2lF/79qv83KlqMjLK55nBjVDyBXHu/jeukrahPXA+IIn+6g7i3+VdEjkdYWDnhlERJAkGre0KPv3fBDaujU79VHDRvJuJW56oKLPWCgR3aRcyPTIpw8qlxyo1bkUYCcUkqiNmUm6MUPxjoBrmZOlDh9BdTtG7kA3PTt5oBgTQaFBR5zaRAafDpDHO+shxP9ODnRnM+wxi35RwJ6HXAz6ZFOdn0JxgaR7rqhit3barETSDDU0MbMovcZAEEaW6VeC08OP40iE8SWKebB5fnJwtPY/jgOz8IIsnZaYSuL1ctNtdBc2LyF3U5FAH3wMpeHOfaPhAoPQLEEnUoyhJrV90KMNYcrUt4RdK47IlRBL8wnFMzgEOU3h9JgP+bkCaLZkan17v1+j33xH/jm8nQJPZH/BiJDGlNyUiehqr9CgF3C+0NTKeWa1/5HxMvhwspSYVTZYkFLBJuNsiAhHqtf4B9mAQVIlllVbepK0+brywZ7sui4uafxBNSLuy44Dt3oKWPqle/CvJXiToKJQoW0bGgK1/SiIWPchRtMQIMfuAjdldWrruWtA0PG7G7Li98yn/gTqNqrYN2dlTs1c2hNWaxoQUSqrsl+4ffz3zS9F5lQBoIW6rOCCzhpFZJu5K3QbBCp8zD2fOTCb4wyGwHyuHpGt6AHq79Ei1E3g=
  - secure: Gs2EYm+dhu7n7pSSOF+2XUm6HpAeGH+cus51bSLd3HO38wWkBjiO5vpVwR7Prr7hdYSC2WPcdlNtrMfdeIJsVpSy+xx4l52M+73Q8lANPAdOwPm+Mi4JhfOmm5xRct3/36YF16tg0jLVzz6g7Ffx5TV72c8gh/FDw5RiNApeb6PcTaamu9P47gNHrcJhydsszl5QUqSjPRmZdC6DTZjqgEiCnn5kBO+01f/QqYQS/fLtqbvb7s+fEqBOEKA7ve760h3y5u34ONPd2YFipRdoYc7jlNnza3CAto0Kg9B/0Uxz3BOCs5hvDy2TFdzWkvWe7xImdcyUcJ/AouwT3Un6H0Edqz0QpE1irZHIQELrVhoTux99FR9W8twGYZGCI8/EfuTeGpGFpS1zMKs5jmavWoKaLbW0JyFMpkhfMAa4TjTd0NwQbaCHusY5LtO6Yf4jdfrXbxhX5gpigOJS2fdUfIj8kanh4AEUxYd1dpj/ghk42kBaUfDsJKhBSOf6Va1hl9qCxA9/2KihfUeokl6xApTYfy26rmyKOOb8c0VaAPy0PJsUe+BsJ4YMLt4TczJtqkiJOM5zy87HIGIDeUBfA8pfRAoDdzCEfrPS5CMoyADUrINSXNmQXmuH5PJu4tmLGLUNoNm6kWovJld/me1zEXjCf9b9o5XMm+TJ3Lgw2w4=
